# Generated by Django 4.2.24 on 2025-11-04 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_averagefee_exchangeuniversity_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_spend_in_korea', models.DecimalField(decimal_places=0, help_text='한국에서의 월 지출 (KRW 기준)', max_digits=12)),
                ('meal_frequency', models.CharField(blank=True, choices=[('1', '하루 1회'), ('2', '하루 2회'), ('3', '하루 3회')], max_length=2, null=True)),
                ('dineout_per_week', models.PositiveIntegerField(default=0)),
                ('coffee_per_week', models.PositiveIntegerField(default=0)),
                ('smoking_per_day', models.PositiveIntegerField(default=0)),
                ('drinking_per_week', models.PositiveIntegerField(default=0)),
                ('shopping_per_month', models.PositiveIntegerField(default=0)),
                ('culture_per_month', models.PositiveIntegerField(default=0)),
                ('residence_type', models.CharField(blank=True, help_text='거주유형 직접 입력', max_length=100)),
                ('commute', models.BooleanField(default=False, help_text='통학여부(통학하면 True)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_detail_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SummarySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detail_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_snapshots', to='summaries.detailprofile')),
                ('exchange_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_snapshots', to='accounts.exchangeprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('snapshot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='summaries.summarysnapshot')),
            ],
        ),
    ]
