# Generated by Django 5.2.8 on 2025-11-08 08:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_spend_in_korea', models.DecimalField(decimal_places=0, help_text='한국에서의 월 지출 (KRW 기준)', max_digits=12)),
                ('meal_frequency', models.CharField(blank=True, choices=[('1', '하루 1회'), ('2', '하루 2회'), ('3', '하루 3회')], max_length=2, null=True)),
                ('dineout_per_week', models.PositiveIntegerField(default=0)),
                ('coffee_per_week', models.PositiveIntegerField(default=0)),
                ('smoking_per_day', models.PositiveIntegerField(default=0)),
                ('drinking_per_week', models.PositiveIntegerField(default=0)),
                ('shopping_per_month', models.PositiveIntegerField(default=0)),
                ('culture_per_month', models.PositiveIntegerField(default=0)),
                ('residence_type', models.CharField(blank=True, help_text='거주유형 직접 입력', max_length=100)),
                ('commute', models.BooleanField(default=False, help_text='통학여부(통학하면 True)')),
                ('summary_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_detail_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SummarySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_nickname', models.CharField(blank=True, max_length=50)),
                ('snapshot_gender', models.CharField(blank=True, max_length=20)),
                ('snapshot_exchange_country', models.CharField(blank=True, max_length=50)),
                ('snapshot_exchange_university', models.CharField(blank=True, max_length=120)),
                ('snapshot_exchange_type', models.CharField(blank=True, max_length=20)),
                ('snapshot_exchange_semester', models.CharField(blank=True, max_length=40)),
                ('snapshot_exchange_period', models.CharField(blank=True, max_length=40)),
                ('living_expense_foreign_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('living_expense_foreign_currency', models.CharField(blank=True, help_text='교환국 통화 코드 (USD, JPY ...)', max_length=5)),
                ('living_expense_krw_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('living_expense_krw_currency', models.CharField(default='KRW', max_length=3)),
                ('base_dispatch_foreign_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('base_dispatch_krw_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detail_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_detail_profile', to='summaries.detailprofile')),
                ('exchange_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_exchange_profile', to='accounts.exchangeprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
