# Generated by Django 4.2.24 on 2025-11-05 07:23

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailprofile',
            name='summary_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='summarysnapshot',
            name='base_dispatch_foreign_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='summarysnapshot',
            name='base_dispatch_krw_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='summarysnapshot',
            name='living_expense_foreign_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='summarysnapshot',
            name='living_expense_foreign_currency',
            field=models.CharField(blank=True, help_text='교환국 통화 코드 (USD, JPY ...)', max_length=5),
        ),
        migrations.AddField(
            model_name='summarysnapshot',
            name='living_expense_krw_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='summarysnapshot',
            name='living_expense_krw_currency',
            field=models.CharField(default='KRW', max_length=3),
        ),
        migrations.AddField(
            model_name='summarysnapshot',
            name='snapshot_exchange_country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='summarysnapshot',
            name='snapshot_exchange_period',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='summarysnapshot',
            name='snapshot_exchange_semester',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='summarysnapshot',
            name='snapshot_exchange_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='summarysnapshot',
            name='snapshot_exchange_university',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='summarysnapshot',
            name='snapshot_gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='summarysnapshot',
            name='snapshot_nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='summarysnapshot',
            name='detail_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_detail_profile', to='summaries.detailprofile'),
        ),
        migrations.AlterField(
            model_name='summarysnapshot',
            name='exchange_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_exchange_profile', to='accounts.exchangeprofile'),
        ),
        migrations.AlterField(
            model_name='summarysnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SummaryNote',
        ),
    ]
