# Generated by Django 4.2.24 on 2025-11-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0004_create_summarysnapshot'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='summarysnapshot',
            table=None,
        ),
    ]
