# Generated by Django 4.2.24 on 2025-11-06 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0003_remove_summarynote_snapshot'),
        ('summaries', '0005_alter_summarysnapshot_table'),
    ]

    operations = [
    ]
