# Generated by Django 4.2.24 on 2025-10-31 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeprofile',
            name='exchange_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_country_students', to='accounts.exchangeuniversity'),
        ),
    ]
