# Generated by Django 4.2.24 on 2025-11-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_exchangeprofile_exchange_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeprofile',
            name='exchange_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
