# Generated by Django 4.2.24 on 2025-11-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_exchangeprofile_exchange_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('USA', '미국'), ('JAPAN', '일본'), ('GERMANY', '독일'), ('FRANCE', '프랑스'), ('CHINA', '중국'), ('TAIWAN', '대만'), ('CANADA', '캐나다'), ('ITALY', '이탈리아'), ('NETHERLANDS', '네덜란드'), ('UK', '영국')], max_length=20)),
                ('flight', models.IntegerField(default=0)),
                ('insurance', models.IntegerField(default=0)),
                ('visa', models.IntegerField(default=0)),
                ('tuition', models.IntegerField(default=0)),
                ('transport', models.IntegerField(default=0)),
                ('food', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='exchangeuniversity',
            name='city',
            field=models.CharField(default='캘리포니아', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchangeuniversity',
            name='country',
            field=models.CharField(choices=[('USA', '미국'), ('JAPAN', '일본'), ('GERMANY', '독일'), ('FRANCE', '프랑스'), ('CHINA', '중국'), ('TAIWAN', '대만'), ('CANADA', '캐나다'), ('ITALY', '이탈리아'), ('NETHERLANDS', '네덜란드'), ('UK', '영국')], max_length=20),
        ),
    ]
