# Generated by Django 4.2.24 on 2025-11-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_exchange_universities'),
        ('accounts', '0004_averagefee_exchangeuniversity_city_and_more'),
    ]

    operations = [
    ]
