# Generated by Django 4.2.24 on 2025-11-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_load_universities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeuniversity',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
