# Generated by Django 4.2.24 on 2025-11-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(blank=True, max_length=10)),
                ('target_currency', models.CharField(blank=True, max_length=10)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('base_currency', 'target_currency', 'effective_at')},
            },
        ),
    ]
