# Generated by Django 4.2.24 on 2025-11-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(blank=True, max_length=10)),
                ('target_currency', models.CharField(choices=[('KRW', '대한민국 원 (KRW)'), ('USD', '미국 달러 (USD)'), ('JPY', '일본 엔 (JPY)'), ('EUR', '유럽 유로 (EUR)'), ('CNY', '중국 위안 (CNY)'), ('TWD', '대만 달러 (TWD)'), ('GBP', '영국 파운드 (GBP)'), ('CAD', '캐나다 달러 (CAD)')], max_length=10, unique=True)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
