# Generated by Django 4.2.24 on 2025-11-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='created_at',
            new_name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('base_currency', 'target_currency', 'updated_at')},
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='effective_at',
        ),
    ]
