# Generated by Django 5.2.8 on 2025-11-08 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('EXPENSE', '지출'), ('INCOME', '수입')], max_length=10)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', '현금'), ('CARD', '카드')], max_length=10, null=True)),
                ('category', models.CharField(choices=[('FOOD', '식비'), ('HOUSING', '주거비'), ('TRANSPORT', '교통비'), ('SHOPPING', '쇼핑비'), ('TRAVEL', '여행비'), ('STUDY_MATERIALS', '교재비'), ('ALLOWANCE', '용돈'), ('ETC', '기타')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_code', models.CharField(max_length=3)),
                ('amount_converted', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('converted_currency_code', models.CharField(blank=True, max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='LedgerEntry에서 몇 월인지 참고')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledgers_user', to=settings.AUTH_USER_MODEL)),
                ('ledger_entries', models.ManyToManyField(blank=True, related_name='ledgers_entries', to='ledgers.ledgerentry')),
            ],
            options={
                'unique_together': {('user', 'month')},
            },
        ),
    ]
