# Generated by Django 4.2.24 on 2025-11-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='month',
            field=models.DateField(help_text='LedgerEntry에서 몇 월인지 참고'),
        ),
    ]
