# Generated by Django 4.2.24 on 2025-11-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='category',
            field=models.CharField(choices=[('FOOD', '식비'), ('HOUSING', '주거비'), ('TRANSPORT', '교통비'), ('SHOPPING', '쇼핑비'), ('TRAVEL', '여행비'), ('STUDY_MATERIALS', '교재비'), ('ALLOWANCE', '용돈'), ('ETC', '기타')], max_length=20),
        ),
    ]
