# Generated by Django 4.2.24 on 2025-11-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0002_alter_ledger_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='converted_currency_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='currency_code',
            field=models.CharField(default='KRW', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='amount_converted',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
