# Generated by Django 4.2.24 on 2025-11-03 11:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledgers', '0003_ledgerentry_converted_currency_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ledger',
            unique_together={('user', 'month')},
        ),
    ]
