# Generated by Django 4.2.24 on 2025-11-03 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledgers', '0004_alter_ledger_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
