# Generated by Django 4.2.24 on 2025-11-06 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount_krw', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LivingBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='living_budget', to='budgets.budget')),
            ],
        ),
        migrations.CreateModel(
            name='LivingBudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FOOD', '식비'), ('TRANSPORT', '교통비'), ('HOUSING', '주거비'), ('SHOPPING', '쇼핑비'), ('CULTURE', '문화생활'), ('TRAVEL', '여행비'), ('TEXTBOOK', '교재비')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('living_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budgets.livingbudget')),
            ],
        ),
        migrations.CreateModel(
            name='BaseBudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FLIGHT', '항공권'), ('INSURANCE', '보험료'), ('VISA', '비자'), ('TUITION', '등록금')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('currency', models.CharField(choices=[('KRW', '대한민국 원 (KRW)'), ('USD', '미국 달러 (USD)'), ('JPY', '일본 엔 (JPY)'), ('EUR', '유럽 유로 (EUR)'), ('CNY', '중국 위안 (CNY)'), ('TWD', '대만 달러 (TWD)'), ('GBP', '영국 파운드 (GBP)'), ('CAD', '캐나다 달러 (CAD)')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budgets.basebudget')),
            ],
        ),
        migrations.AddField(
            model_name='basebudget',
            name='budget',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='base_budget', to='budgets.budget'),
        ),
    ]
