# Generated by Django 5.2.8 on 2025-11-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
